global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: 'brain'
    static_configs:
      - targets: ['svcbrain:8080'] # hard-coded port matches launchSettings.json
  - job_name: 'covers'
    static_configs:
      - targets: ['svccovers:8080'] # hard-coded port matches launchSettings.json
  - job_name: 'metadata'
    scheme: https
    static_configs:
      - targets: ['svcmetadata:8443'] # hard-coded port matches launchSettings.json
  - job_name: 'gateway'
    static_configs:
      - targets: ['svcgateway:8080'] # hard-coded port matches launchSettings.json
