global:
  scrape_interval: 1s # makes for a good demo

scrape_configs:
  - job_name: 'brain'
    static_configs:
      - targets: ['svcbrain:50002'] # hard-coded port matches launchSettings.json
  - job_name: 'covers'
    static_configs:
      - targets: ['svccovers:50003'] # hard-coded port matches launchSettings.json
  - job_name: 'metadata'
    static_configs:
      - targets: ['svcmetadata:50001'] # hard-coded port matches launchSettings.json
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:50000'] # hard-coded port matches launchSettings.json
