// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: brain.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcBrain {
  public static partial class RecognizerMeta
  {
    static readonly string __ServiceName = "GrpcBrain.RecognizerMeta";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcBrain.AddRecognitionNodeRequest> __Marshaller_GrpcBrain_AddRecognitionNodeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcBrain.AddRecognitionNodeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcBrain.AddRecognitionNodeResponse> __Marshaller_GrpcBrain_AddRecognitionNodeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcBrain.AddRecognitionNodeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcBrain.RecognizeTrackRequest> __Marshaller_GrpcBrain_RecognizeTrackRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcBrain.RecognizeTrackRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcBrain.RecognizeTrackResponse> __Marshaller_GrpcBrain_RecognizeTrackResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcBrain.RecognizeTrackResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcBrain.AddRecognitionNodeRequest, global::GrpcBrain.AddRecognitionNodeResponse> __Method_AddRecognitionNode = new grpc::Method<global::GrpcBrain.AddRecognitionNodeRequest, global::GrpcBrain.AddRecognitionNodeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddRecognitionNode",
        __Marshaller_GrpcBrain_AddRecognitionNodeRequest,
        __Marshaller_GrpcBrain_AddRecognitionNodeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcBrain.RecognizeTrackRequest, global::GrpcBrain.RecognizeTrackResponse> __Method_RecognizeTrack = new grpc::Method<global::GrpcBrain.RecognizeTrackRequest, global::GrpcBrain.RecognizeTrackResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RecognizeTrack",
        __Marshaller_GrpcBrain_RecognizeTrackRequest,
        __Marshaller_GrpcBrain_RecognizeTrackResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcBrain.BrainReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RecognizerMeta</summary>
    [grpc::BindServiceMethod(typeof(RecognizerMeta), "BindService")]
    public abstract partial class RecognizerMetaBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcBrain.AddRecognitionNodeResponse> AddRecognitionNode(global::GrpcBrain.AddRecognitionNodeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcBrain.RecognizeTrackResponse> RecognizeTrack(global::GrpcBrain.RecognizeTrackRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RecognizerMeta</summary>
    public partial class RecognizerMetaClient : grpc::ClientBase<RecognizerMetaClient>
    {
      /// <summary>Creates a new client for RecognizerMeta</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RecognizerMetaClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RecognizerMeta that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RecognizerMetaClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RecognizerMetaClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RecognizerMetaClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcBrain.AddRecognitionNodeResponse AddRecognitionNode(global::GrpcBrain.AddRecognitionNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddRecognitionNode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcBrain.AddRecognitionNodeResponse AddRecognitionNode(global::GrpcBrain.AddRecognitionNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddRecognitionNode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcBrain.AddRecognitionNodeResponse> AddRecognitionNodeAsync(global::GrpcBrain.AddRecognitionNodeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddRecognitionNodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcBrain.AddRecognitionNodeResponse> AddRecognitionNodeAsync(global::GrpcBrain.AddRecognitionNodeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddRecognitionNode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcBrain.RecognizeTrackResponse RecognizeTrack(global::GrpcBrain.RecognizeTrackRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RecognizeTrack(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcBrain.RecognizeTrackResponse RecognizeTrack(global::GrpcBrain.RecognizeTrackRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RecognizeTrack, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcBrain.RecognizeTrackResponse> RecognizeTrackAsync(global::GrpcBrain.RecognizeTrackRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RecognizeTrackAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcBrain.RecognizeTrackResponse> RecognizeTrackAsync(global::GrpcBrain.RecognizeTrackRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RecognizeTrack, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override RecognizerMetaClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RecognizerMetaClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(RecognizerMetaBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddRecognitionNode, serviceImpl.AddRecognitionNode)
          .AddMethod(__Method_RecognizeTrack, serviceImpl.RecognizeTrack).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RecognizerMetaBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddRecognitionNode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcBrain.AddRecognitionNodeRequest, global::GrpcBrain.AddRecognitionNodeResponse>(serviceImpl.AddRecognitionNode));
      serviceBinder.AddMethod(__Method_RecognizeTrack, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcBrain.RecognizeTrackRequest, global::GrpcBrain.RecognizeTrackResponse>(serviceImpl.RecognizeTrack));
    }

  }
}
#endregion
