version: "3"
services:
  covers:
    image: significantnose/recognizer-covers
    restart: always
    container_name: covers-service
    environment:
      # apparently, non-prefixed env variable is the way to
      # override the appsettings.json configuration parameters.
      # ideally the application must take the connection string
      # from the env variable. todo.
      - ASPNETCORE_URLS=http://*:80
      - InfrastructureOptions__PostgresConnectionString=User ID=postgres;Host=covers-postgresql;Port=5432;Database=covers;Pooling=true;
    ports:
      - 50003:80

    depends_on:
      covers-postgresql:
        condition: service_healthy

  covers-postgresql:
    image: postgres
    restart: always
    container_name: covers-postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=covers"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "covers"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - 15003:5432
  # redis:
  #   image: redis
  #   restart: always
  #   container_name: local-redis
  #   ports:
  #     - 16379:6379