version: "3"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: covers-postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=covers"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "recognizer"]
      interval: 3s
      timeout: 5s 
      retries: 5
      start_period: 5s
    ports:
      - 15432:5432
  # redis:
  #   image: redis
  #   restart: always
  #   container_name: local-redis
  #   ports:
  #     - 16379:6379
