version: "3"
services:
  metadata:
    image: significantnose/recognizer-metadata
    restart: always
    container_name: metadata-service
    environment:
      # apparently, non-prefixed env variable is the way to 
      # override the appsettings.json configuration parameters.
      # ideally the application must take the connection string
      # from the env variable. todo.
      - ASPNETCORE_URLS=http://*:80 
      - InfrastructureOptions__PostgresConnectionString=User ID=postgres;Host=metadata-postgresql;Port=5432;Database=metadata;Pooling=true;
    ports:
      - 50001:80

    depends_on:
      metadata-postgresql:
        condition: service_healthy

  metadata-postgresql:
    image: postgres
    restart: always
    container_name: metadata-postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=metadata"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "metadata"]
      interval: 3s
      timeout: 5s 
      retries: 5
      start_period: 5s
    ports:
      - 15001:5432
  # redis:
  #   image: redis
  #   restart: always
  #   container_name: local-redis
  #   ports:
  #     - 16379:6379
