// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: albummeta.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcMetadata {
  public static partial class AlbumMetadata
  {
    static readonly string __ServiceName = "GrpcMetadata.AlbumMetadata";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.AddAlbumMetadataRequest> __Marshaller_GrpcMetadata_AddAlbumMetadataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.AddAlbumMetadataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.AddAlbumMetadataResponse> __Marshaller_GrpcMetadata_AddAlbumMetadataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.AddAlbumMetadataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.ReadAlbumMetadataRequest> __Marshaller_GrpcMetadata_ReadAlbumMetadataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.ReadAlbumMetadataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.ReadAlbumMetadataResponse> __Marshaller_GrpcMetadata_ReadAlbumMetadataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.ReadAlbumMetadataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.GetAlbumListByTitleRequest> __Marshaller_GrpcMetadata_GetAlbumListByTitleRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.GetAlbumListByTitleRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.GetAlbumListByTitleResponse> __Marshaller_GrpcMetadata_GetAlbumListByTitleResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.GetAlbumListByTitleResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcMetadata.AddAlbumMetadataRequest, global::GrpcMetadata.AddAlbumMetadataResponse> __Method_AddAlbumMetadata = new grpc::Method<global::GrpcMetadata.AddAlbumMetadataRequest, global::GrpcMetadata.AddAlbumMetadataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddAlbumMetadata",
        __Marshaller_GrpcMetadata_AddAlbumMetadataRequest,
        __Marshaller_GrpcMetadata_AddAlbumMetadataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcMetadata.ReadAlbumMetadataRequest, global::GrpcMetadata.ReadAlbumMetadataResponse> __Method_ReadAlbumMetadata = new grpc::Method<global::GrpcMetadata.ReadAlbumMetadataRequest, global::GrpcMetadata.ReadAlbumMetadataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReadAlbumMetadata",
        __Marshaller_GrpcMetadata_ReadAlbumMetadataRequest,
        __Marshaller_GrpcMetadata_ReadAlbumMetadataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcMetadata.GetAlbumListByTitleRequest, global::GrpcMetadata.GetAlbumListByTitleResponse> __Method_GetAlbumListByTitle = new grpc::Method<global::GrpcMetadata.GetAlbumListByTitleRequest, global::GrpcMetadata.GetAlbumListByTitleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAlbumListByTitle",
        __Marshaller_GrpcMetadata_GetAlbumListByTitleRequest,
        __Marshaller_GrpcMetadata_GetAlbumListByTitleResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcMetadata.AlbummetaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AlbumMetadata</summary>
    [grpc::BindServiceMethod(typeof(AlbumMetadata), "BindService")]
    public abstract partial class AlbumMetadataBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcMetadata.AddAlbumMetadataResponse> AddAlbumMetadata(global::GrpcMetadata.AddAlbumMetadataRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcMetadata.ReadAlbumMetadataResponse> ReadAlbumMetadata(global::GrpcMetadata.ReadAlbumMetadataRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcMetadata.GetAlbumListByTitleResponse> GetAlbumListByTitle(global::GrpcMetadata.GetAlbumListByTitleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AlbumMetadata</summary>
    public partial class AlbumMetadataClient : grpc::ClientBase<AlbumMetadataClient>
    {
      /// <summary>Creates a new client for AlbumMetadata</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AlbumMetadataClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AlbumMetadata that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AlbumMetadataClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AlbumMetadataClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AlbumMetadataClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.AddAlbumMetadataResponse AddAlbumMetadata(global::GrpcMetadata.AddAlbumMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddAlbumMetadata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.AddAlbumMetadataResponse AddAlbumMetadata(global::GrpcMetadata.AddAlbumMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddAlbumMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.AddAlbumMetadataResponse> AddAlbumMetadataAsync(global::GrpcMetadata.AddAlbumMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddAlbumMetadataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.AddAlbumMetadataResponse> AddAlbumMetadataAsync(global::GrpcMetadata.AddAlbumMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddAlbumMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.ReadAlbumMetadataResponse ReadAlbumMetadata(global::GrpcMetadata.ReadAlbumMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadAlbumMetadata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.ReadAlbumMetadataResponse ReadAlbumMetadata(global::GrpcMetadata.ReadAlbumMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReadAlbumMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.ReadAlbumMetadataResponse> ReadAlbumMetadataAsync(global::GrpcMetadata.ReadAlbumMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadAlbumMetadataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.ReadAlbumMetadataResponse> ReadAlbumMetadataAsync(global::GrpcMetadata.ReadAlbumMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReadAlbumMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.GetAlbumListByTitleResponse GetAlbumListByTitle(global::GrpcMetadata.GetAlbumListByTitleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlbumListByTitle(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.GetAlbumListByTitleResponse GetAlbumListByTitle(global::GrpcMetadata.GetAlbumListByTitleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAlbumListByTitle, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.GetAlbumListByTitleResponse> GetAlbumListByTitleAsync(global::GrpcMetadata.GetAlbumListByTitleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlbumListByTitleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.GetAlbumListByTitleResponse> GetAlbumListByTitleAsync(global::GrpcMetadata.GetAlbumListByTitleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAlbumListByTitle, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override AlbumMetadataClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AlbumMetadataClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AlbumMetadataBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddAlbumMetadata, serviceImpl.AddAlbumMetadata)
          .AddMethod(__Method_ReadAlbumMetadata, serviceImpl.ReadAlbumMetadata)
          .AddMethod(__Method_GetAlbumListByTitle, serviceImpl.GetAlbumListByTitle).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AlbumMetadataBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddAlbumMetadata, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcMetadata.AddAlbumMetadataRequest, global::GrpcMetadata.AddAlbumMetadataResponse>(serviceImpl.AddAlbumMetadata));
      serviceBinder.AddMethod(__Method_ReadAlbumMetadata, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcMetadata.ReadAlbumMetadataRequest, global::GrpcMetadata.ReadAlbumMetadataResponse>(serviceImpl.ReadAlbumMetadata));
      serviceBinder.AddMethod(__Method_GetAlbumListByTitle, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcMetadata.GetAlbumListByTitleRequest, global::GrpcMetadata.GetAlbumListByTitleResponse>(serviceImpl.GetAlbumListByTitle));
    }

  }
}
#endregion
