version: "3"
services:
  recognizer:
    image: significantnose/recognizer-brain
    restart: always
    container_name: recognizer-service
    environment:
      # apparently, non-prefixed env variable is the way to 
      # override the appsettings.json configuration parameters.
      # ideally the application must take the connection string
      # from the env variable. todo.
      - ASPNETCORE_URLS=http://*:80 
      - MigrateUp=true
      - InfrastructureOptions__PostgresConnectionString=User ID=postgres;Host=recognizer-postgresql;Port=5432;Database=recognizer;Pooling=true;
    ports:
      - 50002:80

    depends_on:
      recognizer-postgresql:
        condition: service_healthy

  recognizer-postgresql:
    image: postgres
    restart: always
    container_name: recognizer-postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=recognizer"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "recognizer"]
      interval: 3s
      timeout: 5s 
      retries: 5
      start_period: 5s
    ports:
      - 15002:5432
  # redis:
  #   image: redis
  #   restart: always
  #   container_name: local-redis
  #   ports:
  #     - 16379:6379
