using System;
using FluentMigrator;

namespace Infrastructure.Migrations
{
    [Migration(20240310101100, TransactionBehavior.None)]
    public class InitSchema : Migration
    {
        public override void Up()
        {
            const string init_script =             
"""
CREATE TABLE IF NOT EXISTS cover_meta
(
    cover_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    jpg_uri character varying(255) COLLATE pg_catalog."default",
    png_uri character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cover_meta_pkey PRIMARY KEY (cover_id)
);
""";
            Execute.Sql(init_script);
        }

        public override void Down()
        {
            const string init_down_script = 
"""
DROP TABLE cover_meta;
""";
            Execute.Sql(init_down_script);
        }
    }
}
