// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: artistmeta.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcMetadata {
  public static partial class ArtistMetadata
  {
    static readonly string __ServiceName = "GrpcMetadata.ArtistMetadata";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.AddArtistMetadataRequest> __Marshaller_GrpcMetadata_AddArtistMetadataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.AddArtistMetadataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.AddArtistMetadataResponse> __Marshaller_GrpcMetadata_AddArtistMetadataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.AddArtistMetadataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.ReadArtistMetadataRequest> __Marshaller_GrpcMetadata_ReadArtistMetadataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.ReadArtistMetadataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.ReadArtistMetadataResponse> __Marshaller_GrpcMetadata_ReadArtistMetadataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.ReadArtistMetadataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.GetArtistListByStageNameRequest> __Marshaller_GrpcMetadata_GetArtistListByStageNameRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.GetArtistListByStageNameRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.GetArtistListByStageNameResponse> __Marshaller_GrpcMetadata_GetArtistListByStageNameResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.GetArtistListByStageNameResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcMetadata.AddArtistMetadataRequest, global::GrpcMetadata.AddArtistMetadataResponse> __Method_AddArtistMetadata = new grpc::Method<global::GrpcMetadata.AddArtistMetadataRequest, global::GrpcMetadata.AddArtistMetadataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddArtistMetadata",
        __Marshaller_GrpcMetadata_AddArtistMetadataRequest,
        __Marshaller_GrpcMetadata_AddArtistMetadataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcMetadata.ReadArtistMetadataRequest, global::GrpcMetadata.ReadArtistMetadataResponse> __Method_ReadArtistMetadata = new grpc::Method<global::GrpcMetadata.ReadArtistMetadataRequest, global::GrpcMetadata.ReadArtistMetadataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReadArtistMetadata",
        __Marshaller_GrpcMetadata_ReadArtistMetadataRequest,
        __Marshaller_GrpcMetadata_ReadArtistMetadataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcMetadata.GetArtistListByStageNameRequest, global::GrpcMetadata.GetArtistListByStageNameResponse> __Method_GetArtistListByStageName = new grpc::Method<global::GrpcMetadata.GetArtistListByStageNameRequest, global::GrpcMetadata.GetArtistListByStageNameResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetArtistListByStageName",
        __Marshaller_GrpcMetadata_GetArtistListByStageNameRequest,
        __Marshaller_GrpcMetadata_GetArtistListByStageNameResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcMetadata.ArtistmetaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ArtistMetadata</summary>
    [grpc::BindServiceMethod(typeof(ArtistMetadata), "BindService")]
    public abstract partial class ArtistMetadataBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcMetadata.AddArtistMetadataResponse> AddArtistMetadata(global::GrpcMetadata.AddArtistMetadataRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcMetadata.ReadArtistMetadataResponse> ReadArtistMetadata(global::GrpcMetadata.ReadArtistMetadataRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcMetadata.GetArtistListByStageNameResponse> GetArtistListByStageName(global::GrpcMetadata.GetArtistListByStageNameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ArtistMetadata</summary>
    public partial class ArtistMetadataClient : grpc::ClientBase<ArtistMetadataClient>
    {
      /// <summary>Creates a new client for ArtistMetadata</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ArtistMetadataClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ArtistMetadata that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ArtistMetadataClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ArtistMetadataClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ArtistMetadataClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.AddArtistMetadataResponse AddArtistMetadata(global::GrpcMetadata.AddArtistMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddArtistMetadata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.AddArtistMetadataResponse AddArtistMetadata(global::GrpcMetadata.AddArtistMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddArtistMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.AddArtistMetadataResponse> AddArtistMetadataAsync(global::GrpcMetadata.AddArtistMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddArtistMetadataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.AddArtistMetadataResponse> AddArtistMetadataAsync(global::GrpcMetadata.AddArtistMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddArtistMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.ReadArtistMetadataResponse ReadArtistMetadata(global::GrpcMetadata.ReadArtistMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadArtistMetadata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.ReadArtistMetadataResponse ReadArtistMetadata(global::GrpcMetadata.ReadArtistMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReadArtistMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.ReadArtistMetadataResponse> ReadArtistMetadataAsync(global::GrpcMetadata.ReadArtistMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadArtistMetadataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.ReadArtistMetadataResponse> ReadArtistMetadataAsync(global::GrpcMetadata.ReadArtistMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReadArtistMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.GetArtistListByStageNameResponse GetArtistListByStageName(global::GrpcMetadata.GetArtistListByStageNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetArtistListByStageName(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.GetArtistListByStageNameResponse GetArtistListByStageName(global::GrpcMetadata.GetArtistListByStageNameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetArtistListByStageName, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.GetArtistListByStageNameResponse> GetArtistListByStageNameAsync(global::GrpcMetadata.GetArtistListByStageNameRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetArtistListByStageNameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.GetArtistListByStageNameResponse> GetArtistListByStageNameAsync(global::GrpcMetadata.GetArtistListByStageNameRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetArtistListByStageName, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ArtistMetadataClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ArtistMetadataClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ArtistMetadataBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddArtistMetadata, serviceImpl.AddArtistMetadata)
          .AddMethod(__Method_ReadArtistMetadata, serviceImpl.ReadArtistMetadata)
          .AddMethod(__Method_GetArtistListByStageName, serviceImpl.GetArtistListByStageName).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ArtistMetadataBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddArtistMetadata, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcMetadata.AddArtistMetadataRequest, global::GrpcMetadata.AddArtistMetadataResponse>(serviceImpl.AddArtistMetadata));
      serviceBinder.AddMethod(__Method_ReadArtistMetadata, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcMetadata.ReadArtistMetadataRequest, global::GrpcMetadata.ReadArtistMetadataResponse>(serviceImpl.ReadArtistMetadata));
      serviceBinder.AddMethod(__Method_GetArtistListByStageName, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcMetadata.GetArtistListByStageNameRequest, global::GrpcMetadata.GetArtistListByStageNameResponse>(serviceImpl.GetArtistListByStageName));
    }

  }
}
#endregion
