// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: trackmeta.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcMetadata {
  public static partial class TrackMetadata
  {
    static readonly string __ServiceName = "GrpcMetadata.TrackMetadata";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.AddTrackMetadataRequest> __Marshaller_GrpcMetadata_AddTrackMetadataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.AddTrackMetadataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.AddTrackMetadataResponse> __Marshaller_GrpcMetadata_AddTrackMetadataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.AddTrackMetadataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.ReadTrackMetadataRequest> __Marshaller_GrpcMetadata_ReadTrackMetadataRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.ReadTrackMetadataRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.ReadTrackMetadataResponse> __Marshaller_GrpcMetadata_ReadTrackMetadataResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.ReadTrackMetadataResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.GetTrackListByTitleRequest> __Marshaller_GrpcMetadata_GetTrackListByTitleRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.GetTrackListByTitleRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcMetadata.GetTrackListByTitleResponse> __Marshaller_GrpcMetadata_GetTrackListByTitleResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcMetadata.GetTrackListByTitleResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcMetadata.AddTrackMetadataRequest, global::GrpcMetadata.AddTrackMetadataResponse> __Method_AddTrackMetadata = new grpc::Method<global::GrpcMetadata.AddTrackMetadataRequest, global::GrpcMetadata.AddTrackMetadataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddTrackMetadata",
        __Marshaller_GrpcMetadata_AddTrackMetadataRequest,
        __Marshaller_GrpcMetadata_AddTrackMetadataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcMetadata.ReadTrackMetadataRequest, global::GrpcMetadata.ReadTrackMetadataResponse> __Method_ReadTrackMetadata = new grpc::Method<global::GrpcMetadata.ReadTrackMetadataRequest, global::GrpcMetadata.ReadTrackMetadataResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReadTrackMetadata",
        __Marshaller_GrpcMetadata_ReadTrackMetadataRequest,
        __Marshaller_GrpcMetadata_ReadTrackMetadataResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcMetadata.GetTrackListByTitleRequest, global::GrpcMetadata.GetTrackListByTitleResponse> __Method_GetTrackListByTitle = new grpc::Method<global::GrpcMetadata.GetTrackListByTitleRequest, global::GrpcMetadata.GetTrackListByTitleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTrackListByTitle",
        __Marshaller_GrpcMetadata_GetTrackListByTitleRequest,
        __Marshaller_GrpcMetadata_GetTrackListByTitleResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcMetadata.TrackmetaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TrackMetadata</summary>
    [grpc::BindServiceMethod(typeof(TrackMetadata), "BindService")]
    public abstract partial class TrackMetadataBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcMetadata.AddTrackMetadataResponse> AddTrackMetadata(global::GrpcMetadata.AddTrackMetadataRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcMetadata.ReadTrackMetadataResponse> ReadTrackMetadata(global::GrpcMetadata.ReadTrackMetadataRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcMetadata.GetTrackListByTitleResponse> GetTrackListByTitle(global::GrpcMetadata.GetTrackListByTitleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TrackMetadata</summary>
    public partial class TrackMetadataClient : grpc::ClientBase<TrackMetadataClient>
    {
      /// <summary>Creates a new client for TrackMetadata</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TrackMetadataClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TrackMetadata that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TrackMetadataClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TrackMetadataClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TrackMetadataClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.AddTrackMetadataResponse AddTrackMetadata(global::GrpcMetadata.AddTrackMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddTrackMetadata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.AddTrackMetadataResponse AddTrackMetadata(global::GrpcMetadata.AddTrackMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddTrackMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.AddTrackMetadataResponse> AddTrackMetadataAsync(global::GrpcMetadata.AddTrackMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddTrackMetadataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.AddTrackMetadataResponse> AddTrackMetadataAsync(global::GrpcMetadata.AddTrackMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddTrackMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.ReadTrackMetadataResponse ReadTrackMetadata(global::GrpcMetadata.ReadTrackMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadTrackMetadata(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.ReadTrackMetadataResponse ReadTrackMetadata(global::GrpcMetadata.ReadTrackMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReadTrackMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.ReadTrackMetadataResponse> ReadTrackMetadataAsync(global::GrpcMetadata.ReadTrackMetadataRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReadTrackMetadataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.ReadTrackMetadataResponse> ReadTrackMetadataAsync(global::GrpcMetadata.ReadTrackMetadataRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReadTrackMetadata, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.GetTrackListByTitleResponse GetTrackListByTitle(global::GrpcMetadata.GetTrackListByTitleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTrackListByTitle(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcMetadata.GetTrackListByTitleResponse GetTrackListByTitle(global::GrpcMetadata.GetTrackListByTitleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTrackListByTitle, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.GetTrackListByTitleResponse> GetTrackListByTitleAsync(global::GrpcMetadata.GetTrackListByTitleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTrackListByTitleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcMetadata.GetTrackListByTitleResponse> GetTrackListByTitleAsync(global::GrpcMetadata.GetTrackListByTitleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTrackListByTitle, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override TrackMetadataClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TrackMetadataClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(TrackMetadataBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_AddTrackMetadata, serviceImpl.AddTrackMetadata)
          .AddMethod(__Method_ReadTrackMetadata, serviceImpl.ReadTrackMetadata)
          .AddMethod(__Method_GetTrackListByTitle, serviceImpl.GetTrackListByTitle).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TrackMetadataBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_AddTrackMetadata, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcMetadata.AddTrackMetadataRequest, global::GrpcMetadata.AddTrackMetadataResponse>(serviceImpl.AddTrackMetadata));
      serviceBinder.AddMethod(__Method_ReadTrackMetadata, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcMetadata.ReadTrackMetadataRequest, global::GrpcMetadata.ReadTrackMetadataResponse>(serviceImpl.ReadTrackMetadata));
      serviceBinder.AddMethod(__Method_GetTrackListByTitle, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcMetadata.GetTrackListByTitleRequest, global::GrpcMetadata.GetTrackListByTitleResponse>(serviceImpl.GetTrackListByTitle));
    }

  }
}
#endregion
