name: Recognizer CI

on:
  push:
    branches: [ "ci" ]

jobs:
  brain_test_and_publish:
    uses: significantnose/audio_recognizer/.github/workflows/test-and-publish-reusable.yml@ci
    with:
      service-dir-path: ./RecognizerBrain/ 
      service-name: Brain
    secrets: inherit